locals {
  www_bucket_endpoint = aws_s3_bucket_website_configuration.frontend_dev_hosting_config_green.website_endpoint
  non_www_bucket_endpoint = aws_s3_bucket_website_configuration.frontend_dev_hosting_config_blue.website_endpoint
}